### ISSUE TITLE
Explain in README why SDL 1.x is used

### ISSUE THREAD

**Issue by hadess** [flathub/io.gitlab.sdl_jstest.sdl_jstest#2]
I don't know the reasoning behind why the application is built against SDL 1.x, instead of SDL 2.x, but it would help if it were documented in a README file, for example.

**Comment by Grumbel** [comment]
It's simply an application to test how SDL1 games see your joystick, the SDL2 companion app is over at:

https://github.com/flathub/io.gitlab.sdl_jstest.sdl2_jstest

The README is over in upstream at https://github.com/Grumbel/sdl-jstest

flatpak/flathub has right now no way to handle descriptions for command line applications.

**Comment by TingPing** [comment]
> flatpak/flathub has right now no way to handle descriptions for command line applications.

You can install an `appdata` file for a command line app just fine. If it also has an icon and desktop file (which makes sense for curses apps) it will then show up in stores like GNOME-Software and Flathub.

**Comment by Grumbel** [comment]
That's not going to work here as sdl-jstest is controlled by command line option, not ncurses, that's just used for visualisation.

**Comment by TingPing** [comment]
Ah. Well you can still have an appdata file and while graphical stores won't show it `flatpak search` will show it.

**Comment by TingPing** [comment]
Oh it already works:

```
io.gitlab.sdl_jstest.sdl_jstest  269f727            stable flathub            Console based joystick test program for SDL        
io.gitlab.sdl_jstest.sdl2_jstest v0.2.1-10-gb6c9d96 stable flathub            Console based joystick test program for SDL 
```

**Comment by hadess** [comment]
> The README is over in upstream at https://github.com/Grumbel/sdl-jstest

Can you please add a README to this repository so that explains the above ("this is the SDL1 version, the SDL2 version is there")? That's what I was asking in the first place.

**Comment by hadess** [comment]
(and vice-versa in the SDL2 version...)
